
-- 1. Ensure table exists (Idempotent)
create table if not exists public.entrenamientos (
    id_entrenamiento uuid primary key default gen_random_uuid(),
    evento uuid references public.eventos(id) on delete cascade unique,
    calentamiento text default 'No especificado',
    trabajo_separado text default 'No especificado',
    trabajo_conjunto text default 'No especificado',
    objetivos text,
    created_at timestamptz default now()
);

-- 2. Enable RLS if not already enabled
alter table public.entrenamientos enable row level security;

-- 3. Create policies if they don't exist (Drop first to be safe or use DO block)
do $$ 
begin
    if not exists (select 1 from pg_policies where tablename = 'entrenamientos' and policyname = 'Entrenamientos viewable by everyone') then
        create policy "Entrenamientos viewable by everyone" on public.entrenamientos for select using (true);
    end if;

    if not exists (select 1 from pg_policies where tablename = 'entrenamientos' and policyname = 'Staff can manage entranamientos') then
        create policy "Staff can manage entranamientos" on public.entrenamientos for all using (
            exists (select 1 from public.usuarios where id = auth.uid() and tipo_usuario in ('staff', 'admin'))
        );
    end if;
end $$;

-- 4. Backfill missing records
-- Insert a training record for every event of type 'training' (or 'entrenamiento') that doesn't have one
insert into public.entrenamientos (evento, objetivos)
select 
    e.id, 
    coalesce(e.observaciones, 'Autogenerated by fix script')
from public.eventos e
where (lower(e.tipo) like '%training%' or lower(e.tipo) like '%entrenamiento%')
and not exists (
    select 1 from public.entrenamientos t where t.evento = e.id
);

-- 5. Return success message (optional, just checking count)
select count(*) as new_trainings_created from public.entrenamientos 
where created_at > (now() - interval '1 minute');
